/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ferit.hr.lvvjezba;

import java.util.Random;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/*
    1. Korisnik pogađa vrijednost broja definiranog u programu (može biti predefiniran, kao konstanta). Računalo mu
    vraća poruke veći/manji dok god ga ne pogodi. Kada ga pogodi, ispiše mu broj pokušaja (npr. “Bravo! Pogodio/la si
    broj zadan u programu, trebalo ti je 7 pokušaja”).
 */

public class assignment1Main extends javax.swing.JFrame {

    final int definedMax = 10000;
    int guessNumber, tries, limitedTries;
    boolean isLimited;
    /**
     * Creates new form assignment1Main
     */
    public assignment1Main() {
        initComponents();
        initialSetup();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bttnGuess = new javax.swing.JButton();
        lblRange = new javax.swing.JLabel();
        lblRangeValues = new javax.swing.JLabel();
        lblNumOfTries = new javax.swing.JLabel();
        lblNumOfTriesValue = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        lblStatusTxt = new javax.swing.JLabel();
        rbRandom = new javax.swing.JRadioButton();
        rbDefine = new javax.swing.JRadioButton();
        bttnStart = new javax.swing.JButton();
        cbLimitTries = new javax.swing.JCheckBox();
        txtGuess = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Guessing Game");
        setMaximumSize(new java.awt.Dimension(440, 121));
        setMinimumSize(new java.awt.Dimension(531, 121));
        setResizable(false);

        bttnGuess.setFont(new java.awt.Font("Monospaced", 2, 18)); // NOI18N
        bttnGuess.setText("Guess");
        bttnGuess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnGuessActionPerformed(evt);
            }
        });

        lblRange.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        lblRange.setText("Range:");

        lblRangeValues.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        lblRangeValues.setText("1");

        lblNumOfTries.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        lblNumOfTries.setText("Number of tries:");

        lblNumOfTriesValue.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        lblNumOfTriesValue.setText("1");

        lblStatus.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        lblStatus.setText("Status:");

        lblStatusTxt.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        lblStatusTxt.setText("1");

        rbRandom.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        rbRandom.setText("Random range");

        rbDefine.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        rbDefine.setText("Define range");

        bttnStart.setFont(new java.awt.Font("Monospaced", 2, 18)); // NOI18N
        bttnStart.setText("START");
        bttnStart.setMaximumSize(new java.awt.Dimension(119, 32));
        bttnStart.setMinimumSize(new java.awt.Dimension(119, 32));
        bttnStart.setPreferredSize(new java.awt.Dimension(119, 32));
        bttnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnStartActionPerformed(evt);
            }
        });

        cbLimitTries.setFont(new java.awt.Font("Monospaced", 2, 14)); // NOI18N
        cbLimitTries.setText("Limit tries");
        cbLimitTries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLimitTriesActionPerformed(evt);
            }
        });

        txtGuess.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        txtGuess.setMaximumSize(new java.awt.Dimension(256, 30));
        txtGuess.setMinimumSize(new java.awt.Dimension(256, 30));
        txtGuess.setPreferredSize(new java.awt.Dimension(256, 30));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblRange)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblRangeValues))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblStatus)
                            .addComponent(lblNumOfTries))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblStatusTxt, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblNumOfTriesValue, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtGuess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bttnGuess, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbLimitTries))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rbDefine, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rbRandom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bttnStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtGuess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblRange)
                                    .addComponent(lblRangeValues)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(bttnGuess)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbLimitTries)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblNumOfTriesValue)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblStatusTxt))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblNumOfTries)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblStatus))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(rbRandom)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbDefine)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bttnStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbLimitTriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLimitTriesActionPerformed
        do {
            limitedTries = Integer.parseInt(JOptionPane.showInputDialog("Enter number of tries"));
        } while (limitedTries < 1);
        cbLimitTries.setEnabled(false);
    }//GEN-LAST:event_cbLimitTriesActionPerformed

    private void bttnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnStartActionPerformed
        if (rbRandom.isSelected()) {
            guessNumber = defineNumber(0, (definedMax + 1));
            lblRangeValues.setText("[0, " + definedMax + "]");
        } else if (rbDefine.isSelected()) {
            int min, max;
            do {
                min = Integer.parseInt(JOptionPane.showInputDialog(this, "Enter minimum (inclusive)"));
            } while(min < 0);
            do {
                max = Integer.parseInt(JOptionPane.showInputDialog(this, "Enter maximum (exclusive)"));
            } while ((max <= min) || (max > Integer.MAX_VALUE));
            guessNumber = defineNumber(min, max);
            lblRangeValues.setText("[" + min + ", " + (max - 1) + "]");
        }
        tries = 0;
        cbLimitTries.setEnabled(true);
        rbRandom.setEnabled(false);
        rbDefine.setEnabled(false);
        bttnStart.setEnabled(false);
        cbLimitTries.setEnabled(false);
        txtGuess.setEnabled(true);
        txtGuess.requestFocus();
        bttnGuess.setEnabled(true);
        lblRange.setVisible(true);
        lblNumOfTries.setVisible(true);
        lblStatus.setVisible(true);
        if (cbLimitTries.isSelected()) {
            isLimited = true;
            lblNumOfTriesValue.setText("[" + tries + " / " + limitedTries + "]");
        }
        else lblNumOfTriesValue.setText("" + tries);
        lblStatusTxt.setText("Guess");

        bttnStart.setText("" + guessNumber);
    }//GEN-LAST:event_bttnStartActionPerformed

    private void bttnGuessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnGuessActionPerformed
        guess();
    }//GEN-LAST:event_bttnGuessActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(assignment1Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(assignment1Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(assignment1Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(assignment1Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new assignment1Main().setVisible(true);
            }
        });
    }

    public void initialSetup() {
        this.setLocationRelativeTo(null);        
        ButtonGroup grp = new ButtonGroup();
        grp.add(rbRandom);
        grp.add(rbDefine);
        isLimited = false;
        txtGuess.setEnabled(false);
        txtGuess.setText("");        
        bttnGuess.setEnabled(false);
        rbRandom.setSelected(true);        
        lblRange.setVisible(false);
        lblRangeValues.setText("");        
        lblNumOfTries.setVisible(false);
        lblNumOfTriesValue.setText("");        
        lblStatus.setVisible(false);
        lblStatusTxt.setText("");        
        rbRandom.setEnabled(true);
        rbDefine.setEnabled(true);
        bttnStart.setEnabled(true);
        cbLimitTries.setEnabled(true);
        cbLimitTries.setSelected(false);
    }
        
    public static int defineNumber(int min, int max) {
        return new Random().nextInt(max - min) + min;
    }
    
    public void goWin() {
        String message;
        if (!isLimited) {
            message = "Congratulations!\nNumber of tries: " + tries + ".\nDo you want to play again?";
        }
        else {
            message = "Congratulations!\nNumber of tries: [" + tries + " / " + limitedTries + "].\nDo you want to play again?";
        }
        if (JOptionPane.showConfirmDialog(this, message, "Winner!", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            initialSetup();
        }
        else {
            this.dispose();
        }
    }
    
    public void goLose() {
        String message;
        if (!isLimited) {
            message = "Sadly, you lost.\nNumber of tries: " + tries + ".\nDo you want to play again?";
        }
        else {
            message = "Sadly, you lost.\nNumber of tries: [" + tries + " / " + limitedTries + "].\nDo you want to play again?";
        }
        if (JOptionPane.showConfirmDialog(this, message, "Loser!", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            initialSetup();
        }
        else {
            this.dispose();
        }
    }

    public void guess() {
        int guess = Integer.parseInt(txtGuess.getText());
        if (guess > guessNumber) {
            tries++;
            lblStatusTxt.setText("Lower...");
            if (isLimited) {
                lblNumOfTriesValue.setText("[" + tries + " / " + limitedTries + "]");
            }
            else {
                lblNumOfTriesValue.setText("" + tries);
            }            
            if (isLimited && (tries == limitedTries)) {
                goLose();
            }
        } else if (guess < guessNumber) {
            tries++;
            lblStatusTxt.setText("Higher...");
            if (isLimited) {
                lblNumOfTriesValue.setText("[" + tries + " / " + limitedTries + "]");
            }
            else {
                lblNumOfTriesValue.setText("" + tries);
            }            
            if (isLimited && (tries == limitedTries)) {
                goLose();
            }
        } else {
            tries++;
            if (isLimited) {
                lblNumOfTriesValue.setText("[" + tries + " / " + limitedTries + "]");
            }
            else {
                lblNumOfTriesValue.setText("" + tries);
            }
            goWin();
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttnGuess;
    private javax.swing.JButton bttnStart;
    private javax.swing.JCheckBox cbLimitTries;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblNumOfTries;
    private javax.swing.JLabel lblNumOfTriesValue;
    private javax.swing.JLabel lblRange;
    private javax.swing.JLabel lblRangeValues;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblStatusTxt;
    private javax.swing.JRadioButton rbDefine;
    private javax.swing.JRadioButton rbRandom;
    private javax.swing.JTextField txtGuess;
    // End of variables declaration//GEN-END:variables
}
