/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ferit.hr.lv9;

import java.math.BigDecimal;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class assignment1Calculator extends javax.swing.JFrame {

    /**
     * Creates new form assignment1Calculator
     */
    public assignment1Calculator() {
        initComponents();
        this.setLocationRelativeTo(null);
        txtFirstNum.setText("");
        txtSecondNum.setText("");
        txtRes.setText("");
        txtRes.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtFirstNum = new javax.swing.JTextField();
        txtSecondNum = new javax.swing.JTextField();
        cmbOper = new javax.swing.JComboBox<>();
        btnRes = new javax.swing.JButton();
        txtRes = new javax.swing.JTextField();
        btnClear = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator");
        setMaximumSize(new java.awt.Dimension(604, 130));
        setMinimumSize(new java.awt.Dimension(604, 130));
        setResizable(false);

        txtFirstNum.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        txtFirstNum.setMaximumSize(new java.awt.Dimension(245, 30));
        txtFirstNum.setMinimumSize(new java.awt.Dimension(245, 30));
        txtFirstNum.setPreferredSize(new java.awt.Dimension(245, 30));

        txtSecondNum.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        txtSecondNum.setMaximumSize(new java.awt.Dimension(245, 30));
        txtSecondNum.setMinimumSize(new java.awt.Dimension(245, 30));
        txtSecondNum.setPreferredSize(new java.awt.Dimension(245, 30));

        cmbOper.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        cmbOper.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "+", "-", "*", "/" }));
        cmbOper.setMaximumSize(new java.awt.Dimension(90, 30));
        cmbOper.setMinimumSize(new java.awt.Dimension(90, 30));
        cmbOper.setPreferredSize(new java.awt.Dimension(90, 30));

        btnRes.setFont(new java.awt.Font("Lucida Fax", 3, 24)); // NOI18N
        btnRes.setText("RESULT");
        btnRes.setMaximumSize(new java.awt.Dimension(182, 40));
        btnRes.setMinimumSize(new java.awt.Dimension(182, 40));
        btnRes.setPreferredSize(new java.awt.Dimension(182, 40));
        btnRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResActionPerformed(evt);
            }
        });

        txtRes.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        txtRes.setMaximumSize(new java.awt.Dimension(592, 30));
        txtRes.setMinimumSize(new java.awt.Dimension(592, 30));
        txtRes.setPreferredSize(new java.awt.Dimension(592, 30));

        btnClear.setFont(new java.awt.Font("Lucida Fax", 3, 24)); // NOI18N
        btnClear.setText("CLEAR");
        btnClear.setMaximumSize(new java.awt.Dimension(182, 40));
        btnClear.setMinimumSize(new java.awt.Dimension(182, 40));
        btnClear.setPreferredSize(new java.awt.Dimension(182, 40));
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("Lucida Fax", 3, 24)); // NOI18N
        btnExit.setText("EXIT");
        btnExit.setMaximumSize(new java.awt.Dimension(182, 40));
        btnExit.setMinimumSize(new java.awt.Dimension(182, 40));
        btnExit.setPreferredSize(new java.awt.Dimension(182, 40));
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtFirstNum, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbOper, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSecondNum, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtRes, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnRes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(12, 12, 12)
                                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFirstNum, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbOper, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSecondNum, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResActionPerformed
        double numOne, numTwo, res;
        if (txtFirstNum.getText().isBlank() || txtSecondNum.getText().isBlank()) {
            JOptionPane.showMessageDialog(rootPane, "You have to input numbers.");
        } else {
        String oper = cmbOper.getSelectedItem().toString();
        numOne = Double.parseDouble(txtFirstNum.getText());
        numTwo = Double.parseDouble(txtSecondNum.getText());
        switch(oper) {
            case "+" -> {
                res = numOne + numTwo;
                txtRes.setText("" + res);
            }
            case "-" -> {
                res = numOne - numTwo;
                txtRes.setText("" + res);
            }
            case "*" -> {
                res = numOne * numTwo;
                txtRes.setText("" + res);
            }
            case "/" -> {
                if (numTwo == 0) {
                   JOptionPane.showMessageDialog(rootPane, "Division with 0 not allowed.");
                   clearCalc();
                   break;
                }
                res = numOne / numTwo;    
                txtRes.setText("" + res);            
            }
            }
        }
    }//GEN-LAST:event_btnResActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clearCalc();
    }//GEN-LAST:event_btnClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(assignment1Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(assignment1Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(assignment1Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(assignment1Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new assignment1Calculator().setVisible(true);
            }
        });
    }

    public void clearCalc() {
        txtFirstNum.setText("");
        txtSecondNum.setText("");
        txtRes.setText("");
        cmbOper.setSelectedIndex(0);
    }
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnRes;
    private javax.swing.JComboBox<String> cmbOper;
    private javax.swing.JTextField txtFirstNum;
    private javax.swing.JTextField txtRes;
    private javax.swing.JTextField txtSecondNum;
    // End of variables declaration//GEN-END:variables
}
